# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '2_stopWatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  # Pods for 2_stopWatch

end
