# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Analytics'
pod 'SnapKit', '~> 5.0.0'
pod 'Firebase/RemoteConfig'
pod 'TextFieldEffects'

  # Pods for FirebaseExample

end
